language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2

sudo: false

cache: bundler

before_script:
  - git config --global user.email "bot@heroku.com"
  - git config --global user.name "Heroku Bot (Travis CI)"

script: bundle exec rspec spec --color --format documentation

deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: ALsBCGGvdAiIEJR9zTzxumcgCaS5eqOs7Oee7e4SiDgHrT/DRSsFJBtNp9mJvQvHzW3FqSFZU7NO6tSRkwHGdGGw7pf/emjZ2ua0exuyCQ3LaCJBdwSQXl0GTMhhaMCCd2NYWJ+Fa3Q9jWWAdCfV8rqz5AX4ZG6fi3C2uubppVs=
