version: "{build}"
branches:
  only:
    - master
clone_depth: 1
install:
  - ruby --version
  - bundle install -j4
build_script:
  - ocra bin\heroku-ocra data\cacert.pem
test_script:
  - heroku-ocra.exe help
  - heroku-ocra.exe status
artifacts:
  - path: heroku-ocra.exe
    name: heroku-ocra.exe
